name: Update Wallpaper

on:
  schedule:
    # 定时执行，Runs at 18:00 UTC every day
    - cron: '0 18 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: pip install requests
    - name: Run Python script
      run: python main.py
    - name: Commit files
      run: |
        git config --local user.email "867651822@qq.com"
        git config --local user.name "Ohihahaha"
        git add README.md
        git commit -m "Update README.md with new wallpaper"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.MY_GIT_TOKEN }}
        branch: master
