name: Update Wallpaper

on:
  schedule:
    - cron: '0 0 * * *'  # 每天午夜更新

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.7.x'  # 指定 Python 版本为 3.7.x

    - name: Install dependencies
      run: pip install requests

    - name: Update Wallpaper
      run: python main.py
